# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andrie/Ansmine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andrie/Ansmine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/andrie/Ansmine/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrie/Ansmine/CMakeFiles /home/andrie/Ansmine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrie/Ansmine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GethubClient

# Build rule for target.
GethubClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GethubClient
.PHONY : GethubClient

# fast build rule for target.
GethubClient/fast:
	$(MAKE) -f CMakeFiles/GethubClient.dir/build.make CMakeFiles/GethubClient.dir/build
.PHONY : GethubClient/fast

#=============================================================================
# Target rules for targets named RedmineClient

# Build rule for target.
RedmineClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RedmineClient
.PHONY : RedmineClient

# fast build rule for target.
RedmineClient/fast:
	$(MAKE) -f CMakeFiles/RedmineClient.dir/build.make CMakeFiles/RedmineClient.dir/build
.PHONY : RedmineClient/fast

#=============================================================================
# Target rules for targets named ansmine

# Build rule for target.
ansmine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ansmine
.PHONY : ansmine

# fast build rule for target.
ansmine/fast:
	$(MAKE) -f CMakeFiles/ansmine.dir/build.make CMakeFiles/ansmine.dir/build
.PHONY : ansmine/fast

#=============================================================================
# Target rules for targets named ansmined

# Build rule for target.
ansmined: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ansmined
.PHONY : ansmined

# fast build rule for target.
ansmined/fast:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/build
.PHONY : ansmined/fast

qrc_ansmine.o: qrc_ansmine.cxx.o
.PHONY : qrc_ansmine.o

# target to build an object file
qrc_ansmine.cxx.o:
	$(MAKE) -f CMakeFiles/ansmine.dir/build.make CMakeFiles/ansmine.dir/qrc_ansmine.cxx.o
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/qrc_ansmine.cxx.o
.PHONY : qrc_ansmine.cxx.o

qrc_ansmine.i: qrc_ansmine.cxx.i
.PHONY : qrc_ansmine.i

# target to preprocess a source file
qrc_ansmine.cxx.i:
	$(MAKE) -f CMakeFiles/ansmine.dir/build.make CMakeFiles/ansmine.dir/qrc_ansmine.cxx.i
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/qrc_ansmine.cxx.i
.PHONY : qrc_ansmine.cxx.i

qrc_ansmine.s: qrc_ansmine.cxx.s
.PHONY : qrc_ansmine.s

# target to generate assembly for a file
qrc_ansmine.cxx.s:
	$(MAKE) -f CMakeFiles/ansmine.dir/build.make CMakeFiles/ansmine.dir/qrc_ansmine.cxx.s
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/qrc_ansmine.cxx.s
.PHONY : qrc_ansmine.cxx.s

src/ansmined_main.o: src/ansmined_main.cpp.o
.PHONY : src/ansmined_main.o

# target to build an object file
src/ansmined_main.cpp.o:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/ansmined_main.cpp.o
.PHONY : src/ansmined_main.cpp.o

src/ansmined_main.i: src/ansmined_main.cpp.i
.PHONY : src/ansmined_main.i

# target to preprocess a source file
src/ansmined_main.cpp.i:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/ansmined_main.cpp.i
.PHONY : src/ansmined_main.cpp.i

src/ansmined_main.s: src/ansmined_main.cpp.s
.PHONY : src/ansmined_main.s

# target to generate assembly for a file
src/ansmined_main.cpp.s:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/ansmined_main.cpp.s
.PHONY : src/ansmined_main.cpp.s

src/gethub.o: src/gethub.cpp.o
.PHONY : src/gethub.o

# target to build an object file
src/gethub.cpp.o:
	$(MAKE) -f CMakeFiles/GethubClient.dir/build.make CMakeFiles/GethubClient.dir/src/gethub.cpp.o
.PHONY : src/gethub.cpp.o

src/gethub.i: src/gethub.cpp.i
.PHONY : src/gethub.i

# target to preprocess a source file
src/gethub.cpp.i:
	$(MAKE) -f CMakeFiles/GethubClient.dir/build.make CMakeFiles/GethubClient.dir/src/gethub.cpp.i
.PHONY : src/gethub.cpp.i

src/gethub.s: src/gethub.cpp.s
.PHONY : src/gethub.s

# target to generate assembly for a file
src/gethub.cpp.s:
	$(MAKE) -f CMakeFiles/GethubClient.dir/build.make CMakeFiles/GethubClient.dir/src/gethub.cpp.s
.PHONY : src/gethub.cpp.s

src/issue.o: src/issue.cpp.o
.PHONY : src/issue.o

# target to build an object file
src/issue.cpp.o:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/issue.cpp.o
.PHONY : src/issue.cpp.o

src/issue.i: src/issue.cpp.i
.PHONY : src/issue.i

# target to preprocess a source file
src/issue.cpp.i:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/issue.cpp.i
.PHONY : src/issue.cpp.i

src/issue.s: src/issue.cpp.s
.PHONY : src/issue.s

# target to generate assembly for a file
src/issue.cpp.s:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/issue.cpp.s
.PHONY : src/issue.cpp.s

src/login.o: src/login.cpp.o
.PHONY : src/login.o

# target to build an object file
src/login.cpp.o:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/login.cpp.o
.PHONY : src/login.cpp.o

src/login.i: src/login.cpp.i
.PHONY : src/login.i

# target to preprocess a source file
src/login.cpp.i:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/login.cpp.i
.PHONY : src/login.cpp.i

src/login.s: src/login.cpp.s
.PHONY : src/login.s

# target to generate assembly for a file
src/login.cpp.s:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/login.cpp.s
.PHONY : src/login.cpp.s

src/moc_ansmine.o: src/moc_ansmine.cxx.o
.PHONY : src/moc_ansmine.o

# target to build an object file
src/moc_ansmine.cxx.o:
	$(MAKE) -f CMakeFiles/ansmine.dir/build.make CMakeFiles/ansmine.dir/src/moc_ansmine.cxx.o
.PHONY : src/moc_ansmine.cxx.o

src/moc_ansmine.i: src/moc_ansmine.cxx.i
.PHONY : src/moc_ansmine.i

# target to preprocess a source file
src/moc_ansmine.cxx.i:
	$(MAKE) -f CMakeFiles/ansmine.dir/build.make CMakeFiles/ansmine.dir/src/moc_ansmine.cxx.i
.PHONY : src/moc_ansmine.cxx.i

src/moc_ansmine.s: src/moc_ansmine.cxx.s
.PHONY : src/moc_ansmine.s

# target to generate assembly for a file
src/moc_ansmine.cxx.s:
	$(MAKE) -f CMakeFiles/ansmine.dir/build.make CMakeFiles/ansmine.dir/src/moc_ansmine.cxx.s
.PHONY : src/moc_ansmine.cxx.s

src/moc_gethub.o: src/moc_gethub.cxx.o
.PHONY : src/moc_gethub.o

# target to build an object file
src/moc_gethub.cxx.o:
	$(MAKE) -f CMakeFiles/GethubClient.dir/build.make CMakeFiles/GethubClient.dir/src/moc_gethub.cxx.o
.PHONY : src/moc_gethub.cxx.o

src/moc_gethub.i: src/moc_gethub.cxx.i
.PHONY : src/moc_gethub.i

# target to preprocess a source file
src/moc_gethub.cxx.i:
	$(MAKE) -f CMakeFiles/GethubClient.dir/build.make CMakeFiles/GethubClient.dir/src/moc_gethub.cxx.i
.PHONY : src/moc_gethub.cxx.i

src/moc_gethub.s: src/moc_gethub.cxx.s
.PHONY : src/moc_gethub.s

# target to generate assembly for a file
src/moc_gethub.cxx.s:
	$(MAKE) -f CMakeFiles/GethubClient.dir/build.make CMakeFiles/GethubClient.dir/src/moc_gethub.cxx.s
.PHONY : src/moc_gethub.cxx.s

src/moc_login.o: src/moc_login.cxx.o
.PHONY : src/moc_login.o

# target to build an object file
src/moc_login.cxx.o:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/moc_login.cxx.o
.PHONY : src/moc_login.cxx.o

src/moc_login.i: src/moc_login.cxx.i
.PHONY : src/moc_login.i

# target to preprocess a source file
src/moc_login.cxx.i:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/moc_login.cxx.i
.PHONY : src/moc_login.cxx.i

src/moc_login.s: src/moc_login.cxx.s
.PHONY : src/moc_login.s

# target to generate assembly for a file
src/moc_login.cxx.s:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/moc_login.cxx.s
.PHONY : src/moc_login.cxx.s

src/moc_redmine.o: src/moc_redmine.cxx.o
.PHONY : src/moc_redmine.o

# target to build an object file
src/moc_redmine.cxx.o:
	$(MAKE) -f CMakeFiles/RedmineClient.dir/build.make CMakeFiles/RedmineClient.dir/src/moc_redmine.cxx.o
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/moc_redmine.cxx.o
.PHONY : src/moc_redmine.cxx.o

src/moc_redmine.i: src/moc_redmine.cxx.i
.PHONY : src/moc_redmine.i

# target to preprocess a source file
src/moc_redmine.cxx.i:
	$(MAKE) -f CMakeFiles/RedmineClient.dir/build.make CMakeFiles/RedmineClient.dir/src/moc_redmine.cxx.i
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/moc_redmine.cxx.i
.PHONY : src/moc_redmine.cxx.i

src/moc_redmine.s: src/moc_redmine.cxx.s
.PHONY : src/moc_redmine.s

# target to generate assembly for a file
src/moc_redmine.cxx.s:
	$(MAKE) -f CMakeFiles/RedmineClient.dir/build.make CMakeFiles/RedmineClient.dir/src/moc_redmine.cxx.s
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/moc_redmine.cxx.s
.PHONY : src/moc_redmine.cxx.s

src/moc_settings_chat.o: src/moc_settings_chat.cxx.o
.PHONY : src/moc_settings_chat.o

# target to build an object file
src/moc_settings_chat.cxx.o:
	$(MAKE) -f CMakeFiles/ansmine.dir/build.make CMakeFiles/ansmine.dir/src/moc_settings_chat.cxx.o
.PHONY : src/moc_settings_chat.cxx.o

src/moc_settings_chat.i: src/moc_settings_chat.cxx.i
.PHONY : src/moc_settings_chat.i

# target to preprocess a source file
src/moc_settings_chat.cxx.i:
	$(MAKE) -f CMakeFiles/ansmine.dir/build.make CMakeFiles/ansmine.dir/src/moc_settings_chat.cxx.i
.PHONY : src/moc_settings_chat.cxx.i

src/moc_settings_chat.s: src/moc_settings_chat.cxx.s
.PHONY : src/moc_settings_chat.s

# target to generate assembly for a file
src/moc_settings_chat.cxx.s:
	$(MAKE) -f CMakeFiles/ansmine.dir/build.make CMakeFiles/ansmine.dir/src/moc_settings_chat.cxx.s
.PHONY : src/moc_settings_chat.cxx.s

src/moc_tray.o: src/moc_tray.cxx.o
.PHONY : src/moc_tray.o

# target to build an object file
src/moc_tray.cxx.o:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/moc_tray.cxx.o
.PHONY : src/moc_tray.cxx.o

src/moc_tray.i: src/moc_tray.cxx.i
.PHONY : src/moc_tray.i

# target to preprocess a source file
src/moc_tray.cxx.i:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/moc_tray.cxx.i
.PHONY : src/moc_tray.cxx.i

src/moc_tray.s: src/moc_tray.cxx.s
.PHONY : src/moc_tray.s

# target to generate assembly for a file
src/moc_tray.cxx.s:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/moc_tray.cxx.s
.PHONY : src/moc_tray.cxx.s

src/redmine.o: src/redmine.cpp.o
.PHONY : src/redmine.o

# target to build an object file
src/redmine.cpp.o:
	$(MAKE) -f CMakeFiles/RedmineClient.dir/build.make CMakeFiles/RedmineClient.dir/src/redmine.cpp.o
.PHONY : src/redmine.cpp.o

src/redmine.i: src/redmine.cpp.i
.PHONY : src/redmine.i

# target to preprocess a source file
src/redmine.cpp.i:
	$(MAKE) -f CMakeFiles/RedmineClient.dir/build.make CMakeFiles/RedmineClient.dir/src/redmine.cpp.i
.PHONY : src/redmine.cpp.i

src/redmine.s: src/redmine.cpp.s
.PHONY : src/redmine.s

# target to generate assembly for a file
src/redmine.cpp.s:
	$(MAKE) -f CMakeFiles/RedmineClient.dir/build.make CMakeFiles/RedmineClient.dir/src/redmine.cpp.s
.PHONY : src/redmine.cpp.s

src/redmine_model.o: src/redmine_model.cpp.o
.PHONY : src/redmine_model.o

# target to build an object file
src/redmine_model.cpp.o:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/redmine_model.cpp.o
.PHONY : src/redmine_model.cpp.o

src/redmine_model.i: src/redmine_model.cpp.i
.PHONY : src/redmine_model.i

# target to preprocess a source file
src/redmine_model.cpp.i:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/redmine_model.cpp.i
.PHONY : src/redmine_model.cpp.i

src/redmine_model.s: src/redmine_model.cpp.s
.PHONY : src/redmine_model.s

# target to generate assembly for a file
src/redmine_model.cpp.s:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/redmine_model.cpp.s
.PHONY : src/redmine_model.cpp.s

src/tray.o: src/tray.cpp.o
.PHONY : src/tray.o

# target to build an object file
src/tray.cpp.o:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/tray.cpp.o
.PHONY : src/tray.cpp.o

src/tray.i: src/tray.cpp.i
.PHONY : src/tray.i

# target to preprocess a source file
src/tray.cpp.i:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/tray.cpp.i
.PHONY : src/tray.cpp.i

src/tray.s: src/tray.cpp.s
.PHONY : src/tray.s

# target to generate assembly for a file
src/tray.cpp.s:
	$(MAKE) -f CMakeFiles/ansmined.dir/build.make CMakeFiles/ansmined.dir/src/tray.cpp.s
.PHONY : src/tray.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... GethubClient"
	@echo "... RedmineClient"
	@echo "... ansmine"
	@echo "... ansmined"
	@echo "... edit_cache"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... qrc_ansmine.o"
	@echo "... qrc_ansmine.i"
	@echo "... qrc_ansmine.s"
	@echo "... src/ansmined_main.o"
	@echo "... src/ansmined_main.i"
	@echo "... src/ansmined_main.s"
	@echo "... src/gethub.o"
	@echo "... src/gethub.i"
	@echo "... src/gethub.s"
	@echo "... src/issue.o"
	@echo "... src/issue.i"
	@echo "... src/issue.s"
	@echo "... src/login.o"
	@echo "... src/login.i"
	@echo "... src/login.s"
	@echo "... src/moc_ansmine.o"
	@echo "... src/moc_ansmine.i"
	@echo "... src/moc_ansmine.s"
	@echo "... src/moc_gethub.o"
	@echo "... src/moc_gethub.i"
	@echo "... src/moc_gethub.s"
	@echo "... src/moc_login.o"
	@echo "... src/moc_login.i"
	@echo "... src/moc_login.s"
	@echo "... src/moc_redmine.o"
	@echo "... src/moc_redmine.i"
	@echo "... src/moc_redmine.s"
	@echo "... src/moc_settings_chat.o"
	@echo "... src/moc_settings_chat.i"
	@echo "... src/moc_settings_chat.s"
	@echo "... src/moc_tray.o"
	@echo "... src/moc_tray.i"
	@echo "... src/moc_tray.s"
	@echo "... src/redmine.o"
	@echo "... src/redmine.i"
	@echo "... src/redmine.s"
	@echo "... src/redmine_model.o"
	@echo "... src/redmine_model.i"
	@echo "... src/redmine_model.s"
	@echo "... src/tray.o"
	@echo "... src/tray.i"
	@echo "... src/tray.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

