# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/robin/Development/ansvia/ansmine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/robin/Development/ansvia/ansmine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/robin/Development/ansvia/ansmine/CMakeFiles /Users/robin/Development/ansvia/ansmine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/robin/Development/ansvia/ansmine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Ansmine

# Build rule for target.
Ansmine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Ansmine
.PHONY : Ansmine

# fast build rule for target.
Ansmine/fast:
	$(MAKE) -f CMakeFiles/Ansmine.dir/build.make CMakeFiles/Ansmine.dir/build
.PHONY : Ansmine/fast

#=============================================================================
# Target rules for targets named Ansmined

# Build rule for target.
Ansmined: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Ansmined
.PHONY : Ansmined

# fast build rule for target.
Ansmined/fast:
	$(MAKE) -f CMakeFiles/Ansmined.dir/build.make CMakeFiles/Ansmined.dir/build
.PHONY : Ansmined/fast

src/ansmine.o: src/ansmine.cpp.o
.PHONY : src/ansmine.o

# target to build an object file
src/ansmine.cpp.o:
	$(MAKE) -f CMakeFiles/Ansmine.dir/build.make CMakeFiles/Ansmine.dir/src/ansmine.cpp.o
.PHONY : src/ansmine.cpp.o

src/ansmine.i: src/ansmine.cpp.i
.PHONY : src/ansmine.i

# target to preprocess a source file
src/ansmine.cpp.i:
	$(MAKE) -f CMakeFiles/Ansmine.dir/build.make CMakeFiles/Ansmine.dir/src/ansmine.cpp.i
.PHONY : src/ansmine.cpp.i

src/ansmine.s: src/ansmine.cpp.s
.PHONY : src/ansmine.s

# target to generate assembly for a file
src/ansmine.cpp.s:
	$(MAKE) -f CMakeFiles/Ansmine.dir/build.make CMakeFiles/Ansmine.dir/src/ansmine.cpp.s
.PHONY : src/ansmine.cpp.s

src/ansmine_main.o: src/ansmine_main.cpp.o
.PHONY : src/ansmine_main.o

# target to build an object file
src/ansmine_main.cpp.o:
	$(MAKE) -f CMakeFiles/Ansmine.dir/build.make CMakeFiles/Ansmine.dir/src/ansmine_main.cpp.o
.PHONY : src/ansmine_main.cpp.o

src/ansmine_main.i: src/ansmine_main.cpp.i
.PHONY : src/ansmine_main.i

# target to preprocess a source file
src/ansmine_main.cpp.i:
	$(MAKE) -f CMakeFiles/Ansmine.dir/build.make CMakeFiles/Ansmine.dir/src/ansmine_main.cpp.i
.PHONY : src/ansmine_main.cpp.i

src/ansmine_main.s: src/ansmine_main.cpp.s
.PHONY : src/ansmine_main.s

# target to generate assembly for a file
src/ansmine_main.cpp.s:
	$(MAKE) -f CMakeFiles/Ansmine.dir/build.make CMakeFiles/Ansmine.dir/src/ansmine_main.cpp.s
.PHONY : src/ansmine_main.cpp.s

src/ansmined_main.o: src/ansmined_main.cpp.o
.PHONY : src/ansmined_main.o

# target to build an object file
src/ansmined_main.cpp.o:
	$(MAKE) -f CMakeFiles/Ansmined.dir/build.make CMakeFiles/Ansmined.dir/src/ansmined_main.cpp.o
.PHONY : src/ansmined_main.cpp.o

src/ansmined_main.i: src/ansmined_main.cpp.i
.PHONY : src/ansmined_main.i

# target to preprocess a source file
src/ansmined_main.cpp.i:
	$(MAKE) -f CMakeFiles/Ansmined.dir/build.make CMakeFiles/Ansmined.dir/src/ansmined_main.cpp.i
.PHONY : src/ansmined_main.cpp.i

src/ansmined_main.s: src/ansmined_main.cpp.s
.PHONY : src/ansmined_main.s

# target to generate assembly for a file
src/ansmined_main.cpp.s:
	$(MAKE) -f CMakeFiles/Ansmined.dir/build.make CMakeFiles/Ansmined.dir/src/ansmined_main.cpp.s
.PHONY : src/ansmined_main.cpp.s

src/moc_ansmine.o: src/moc_ansmine.cxx.o
.PHONY : src/moc_ansmine.o

# target to build an object file
src/moc_ansmine.cxx.o:
	$(MAKE) -f CMakeFiles/Ansmine.dir/build.make CMakeFiles/Ansmine.dir/src/moc_ansmine.cxx.o
.PHONY : src/moc_ansmine.cxx.o

src/moc_ansmine.i: src/moc_ansmine.cxx.i
.PHONY : src/moc_ansmine.i

# target to preprocess a source file
src/moc_ansmine.cxx.i:
	$(MAKE) -f CMakeFiles/Ansmine.dir/build.make CMakeFiles/Ansmine.dir/src/moc_ansmine.cxx.i
.PHONY : src/moc_ansmine.cxx.i

src/moc_ansmine.s: src/moc_ansmine.cxx.s
.PHONY : src/moc_ansmine.s

# target to generate assembly for a file
src/moc_ansmine.cxx.s:
	$(MAKE) -f CMakeFiles/Ansmine.dir/build.make CMakeFiles/Ansmine.dir/src/moc_ansmine.cxx.s
.PHONY : src/moc_ansmine.cxx.s

src/moc_tray.o: src/moc_tray.cxx.o
.PHONY : src/moc_tray.o

# target to build an object file
src/moc_tray.cxx.o:
	$(MAKE) -f CMakeFiles/Ansmined.dir/build.make CMakeFiles/Ansmined.dir/src/moc_tray.cxx.o
.PHONY : src/moc_tray.cxx.o

src/moc_tray.i: src/moc_tray.cxx.i
.PHONY : src/moc_tray.i

# target to preprocess a source file
src/moc_tray.cxx.i:
	$(MAKE) -f CMakeFiles/Ansmined.dir/build.make CMakeFiles/Ansmined.dir/src/moc_tray.cxx.i
.PHONY : src/moc_tray.cxx.i

src/moc_tray.s: src/moc_tray.cxx.s
.PHONY : src/moc_tray.s

# target to generate assembly for a file
src/moc_tray.cxx.s:
	$(MAKE) -f CMakeFiles/Ansmined.dir/build.make CMakeFiles/Ansmined.dir/src/moc_tray.cxx.s
.PHONY : src/moc_tray.cxx.s

src/tray.o: src/tray.cpp.o
.PHONY : src/tray.o

# target to build an object file
src/tray.cpp.o:
	$(MAKE) -f CMakeFiles/Ansmined.dir/build.make CMakeFiles/Ansmined.dir/src/tray.cpp.o
.PHONY : src/tray.cpp.o

src/tray.i: src/tray.cpp.i
.PHONY : src/tray.i

# target to preprocess a source file
src/tray.cpp.i:
	$(MAKE) -f CMakeFiles/Ansmined.dir/build.make CMakeFiles/Ansmined.dir/src/tray.cpp.i
.PHONY : src/tray.cpp.i

src/tray.s: src/tray.cpp.s
.PHONY : src/tray.s

# target to generate assembly for a file
src/tray.cpp.s:
	$(MAKE) -f CMakeFiles/Ansmined.dir/build.make CMakeFiles/Ansmined.dir/src/tray.cpp.s
.PHONY : src/tray.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Ansmine"
	@echo "... Ansmined"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/ansmine.o"
	@echo "... src/ansmine.i"
	@echo "... src/ansmine.s"
	@echo "... src/ansmine_main.o"
	@echo "... src/ansmine_main.i"
	@echo "... src/ansmine_main.s"
	@echo "... src/ansmined_main.o"
	@echo "... src/ansmined_main.i"
	@echo "... src/ansmined_main.s"
	@echo "... src/moc_ansmine.o"
	@echo "... src/moc_ansmine.i"
	@echo "... src/moc_ansmine.s"
	@echo "... src/moc_tray.o"
	@echo "... src/moc_tray.i"
	@echo "... src/moc_tray.s"
	@echo "... src/tray.o"
	@echo "... src/tray.i"
	@echo "... src/tray.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

